# Generated by Django 2.2.5 on 2019-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='user',
            field=models.CharField(max_length=20, verbose_name='User'),
        ),
    ]
