# Generated by Django 2.2.5 on 2019-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstore', '0003_auto_20191019_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banerleft',
            name='banner_left',
            field=models.ImageField(upload_to='bannersleft'),
        ),
        migrations.AlterField(
            model_name='banerright',
            name='banner_right',
            field=models.ImageField(upload_to='bannersright'),
        ),
        migrations.AlterField(
            model_name='banertop',
            name='banner_top',
            field=models.ImageField(upload_to='banerstop'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='img',
            field=models.ImageField(upload_to='topproducts', verbose_name='Şəkil'),
        ),
    ]
